"""initial_oauth_and_auth_schema

Revision ID: 8c8a30de2936
Revises: 
Create Date: 2026-02-27 12:03:13.468743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c8a30de2936'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', 'GITHUB', name='authprovider', schema='noavoice_ns'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='noavoice_ns'
    )
    op.create_index(op.f('ix_noavoice_ns_tbl_users_email'), 'tbl_users', ['email'], unique=True, schema='noavoice_ns')
    op.create_index(op.f('ix_noavoice_ns_tbl_users_provider_id'), 'tbl_users', ['provider_id'], unique=False, schema='noavoice_ns')
    op.create_table('tbl_bookings',
    sa.Column('calcom_booking_id', sa.Integer(), nullable=True),
    sa.Column('calcom_booking_uid', sa.String(length=255), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=True),
    sa.Column('patient_timezone', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('rescheduling_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('livekit_session_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'ACCEPTED', 'CANCELLED', 'RESCHEDULED')", name='check_booking_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_bookings_calcom_booking_uid'), 'tbl_bookings', ['calcom_booking_uid'], unique=False)
    op.create_index(op.f('ix_tbl_bookings_patient_email'), 'tbl_bookings', ['patient_email'], unique=False)
    op.create_table('tbl_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['noavoice_ns.tbl_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='noavoice_ns'
    )
    op.create_index('ix_refresh_tokens_token_hash', 'tbl_refresh_tokens', ['token_hash'], unique=False, schema='noavoice_ns')
    op.create_index('ix_refresh_tokens_user_id', 'tbl_refresh_tokens', ['user_id'], unique=False, schema='noavoice_ns')
    op.drop_index(op.f('ix_noavoice_agents_id'), table_name='noavoice_agents')
    op.drop_index(op.f('ix_noavoice_agents_user_id'), table_name='noavoice_agents')
    op.drop_table('noavoice_agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_phone_numbers_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_actions_agent_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['noavoice_agents.id'], name=op.f('actions_agent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('actions_pkey'))
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_index(op.f('ix_actions_agent_id'), 'actions', ['agent_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['noavoice_agents.id'], name=op.f('audit_logs_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'processed'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['noavoice_agents.id'], name=op.f('knowledge_bases_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('knowledge_bases_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_bases_pkey'))
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('twilio_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('friendly_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['noavoice_agents.id'], name=op.f('phone_numbers_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('phone_numbers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('phone_numbers_pkey')),
    sa.UniqueConstraint('twilio_number', name=op.f('phone_numbers_twilio_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_phone_numbers_id'), 'phone_numbers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('picture', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_oauth_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('google_id', name=op.f('users_google_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('noavoice_agents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voice', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('first_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_message_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('end_call_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voicemail_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recording_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hipaa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('detect_caller_number', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('forwarding_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('summary_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('voice_provider', sa.VARCHAR(length=50), server_default=sa.text("'elevenlabs'::character varying"), autoincrement=False, nullable=True),
    sa.Column('model_provider', sa.VARCHAR(length=50), server_default=sa.text("'openai'::character varying"), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), server_default=sa.text("'gpt-4o'::character varying"), autoincrement=False, nullable=True),
    sa.Column('transcriber', sa.VARCHAR(length=50), server_default=sa.text("'deepgram'::character varying"), autoincrement=False, nullable=True),
    sa.Column('multilingual_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('noavoice_agents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('noavoice_agents_pkey'))
    )
    op.create_index(op.f('ix_noavoice_agents_user_id'), 'noavoice_agents', ['user_id'], unique=False)
    op.create_index(op.f('ix_noavoice_agents_id'), 'noavoice_agents', ['id'], unique=False)
    op.drop_index('ix_refresh_tokens_user_id', table_name='tbl_refresh_tokens', schema='noavoice_ns')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='tbl_refresh_tokens', schema='noavoice_ns')
    op.drop_table('tbl_refresh_tokens', schema='noavoice_ns')
    op.drop_index(op.f('ix_tbl_bookings_patient_email'), table_name='tbl_bookings')
    op.drop_index(op.f('ix_tbl_bookings_calcom_booking_uid'), table_name='tbl_bookings')
    op.drop_table('tbl_bookings')
    op.drop_index(op.f('ix_noavoice_ns_tbl_users_provider_id'), table_name='tbl_users', schema='noavoice_ns')
    op.drop_index(op.f('ix_noavoice_ns_tbl_users_email'), table_name='tbl_users', schema='noavoice_ns')
    op.drop_table('tbl_users', schema='noavoice_ns')
    # ### end Alembic commands ###
